### ISSUE TITLE
Make the Frontend look better 😢

### ISSUE THREAD

**Issue by cfereday** [cfereday/todo-app#6]
<img width="290" alt="Screenshot 2020-05-25 at 12 31 45" src="https://user-images.githubusercontent.com/53565854/82805117-bf8fd400-9e83-11ea-96d6-a7a81a352496.png">

**Comment by cfereday** [comment]
<img width="228" alt="Screenshot 2020-05-25 at 14 15 02" src="https://user-images.githubusercontent.com/53565854/82811941-38962800-9e92-11ea-9c5e-5842a805e366.png">

CSS is now *a thing* in the App. Needs a lot more work to get there but WIP.

**Comment by devloves** [comment]
hi i am a frontend designer i can make it look better :)

**Comment by cfereday** [comment]
Hi @devloves thanks for the offer. This is a learning project for me so I write issues to myself as tasks not to forget. I'm aiming to improve UI skills so will be doing the styling myself but thanks for the offer.

**Comment by cfereday** [comment]
[This](https://kognise.github.io/water.css/) looks cool

**Comment by cfereday** [comment]
Implented water.css to have some basic styling while I focus on React.
<img width="427" alt="Screenshot 2020-05-31 at 11 54 12" src="https://user-images.githubusercontent.com/53565854/83349500-a4b2d900-a335-11ea-811d-5cff0059e863.png">
